name: Build and run test image

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and run test image
        uses: docker compose up --build --abort-on-container-exit --exit-code-from app
